### ISSUE TITLE
Bad_TcpMessageTooLarge message size exceeds configured limit

### ISSUE THREAD

**Issue by coreteam-co** [eclipse/milo#1127]
**Describe the bug**
When performing a history read we are receiving the following exception:

```Bad_TcpMessageTooLarge message size exceeds configured limit```

We already tried to set `setMaxResponseMessageSize` to a larger value (e.g. `50000`) but it did not change the behaviour.

**Expected behavior**
Should work without exception

**Logs and Packet Captures**
```
2023-05-24T14:34:54,562 [milo-shared-thread-pool-2] WARN  io.netty.util.ReferenceCountUtil - Failed to release a message: UnpooledSlicedByteBuf(freed)
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[netty-buffer-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.buffer.AbstractDerivedByteBuf.release0(AbstractDerivedByteBuf.java:98) ~[netty-buffer-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:94) ~[netty-buffer-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:116) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder.decode(ChunkDecoder.java:96) ~[stack-core-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder.decodeSymmetric(ChunkDecoder.java:77) ~[stack-core-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.client.transport.uasc.UascClientMessageHandler.lambda$onSecureMessage$14(UascClientMessageHandler.java:623) ~[stack-client-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.core.channel.SerializationQueue.lambda$decode$1(SerializationQueue.java:56) ~[stack-core-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$Task.run(ExecutionQueue.java:119) ~[stack-core-0.6.9.jar:0.6.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
2023-05-24T14:34:54,563 [milo-shared-thread-pool-2] ERROR org.eclipse.milo.opcua.stack.client.transport.uasc.UascClientMessageHandler - Error decoding symmetric message
org.eclipse.milo.opcua.stack.core.channel.MessageDecodeException: UaException: status=Bad_TcpMessageTooLarge, message=message size exceeds configured limit: 3055681 > 2097152
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder.decode(ChunkDecoder.java:97) ~[stack-core-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder.decodeSymmetric(ChunkDecoder.java:77) ~[stack-core-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.client.transport.uasc.UascClientMessageHandler.lambda$onSecureMessage$14(UascClientMessageHandler.java:623) ~[stack-client-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.core.channel.SerializationQueue.lambda$decode$1(SerializationQueue.java:56) ~[stack-core-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$Task.run(ExecutionQueue.java:119) ~[stack-core-0.6.9.jar:0.6.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: org.eclipse.milo.opcua.stack.core.UaException: message size exceeds configured limit: 3055681 > 2097152
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder$AbstractDecoder.decode(ChunkDecoder.java:241) ~[stack-core-0.6.9.jar:0.6.9]
	at org.eclipse.milo.opcua.stack.core.channel.ChunkDecoder.decode(ChunkDecoder.java:89) ~[stack-core-0.6.9.jar:0.6.9]
	... 7 more
```

**Additional context**
Milo version `0.6.9`
OPC UA Server is Siemens WinCC

**Comment by kevinherron** [comment]
You would need to request less data - this error is because the message coming from the server is larger than the configured limits.

**Comment by coreteam-co** [comment]
Thanks for you fast response. I was under the assumption the server would chunk the data and I can use continuation points to even retrieve large data sets. Isn't this the case? Thanks for you support!

**Comment by kevinherron** [comment]
That is how it works, but the server is currently returning a response larger than allowed by the negotiated channel parameters.

Is this a HistoryReadRequest? How many `HistoryReadValueId` are you supplying for the `nodesToRead` parameter?

**Comment by kevinherron** [comment]
In `ReadRawModifiedDetails` you can try setting a non-zero value for `numValuesPerNode`, or a smaller value if it's non-zero already.

If that doesn't work the server isn't doing its job right and you may need to try increasing the channel limits. Look at the `EncodingLimits` class and `UaStackClientConfigBuilder::setEncodingLimits`.
