### ISSUE TITLE
Bad_OutOfMemory

### ISSUE THREAD

**Issue by ohaTgxK9956562414460** [eclipse/milo#1137]
This error occurred while browsing the tag

17:21:22.794 [milo-shared-thread-pool-4] WARN  o.e.m.opcua.sdk.client.AddressSpace - Failed to create Node from Reference to ExpandedNodeId{ns=2, id=XBD.GML.ZDW_2106CY, serverIndex=0}
java.util.concurrent.CompletionException: UaServiceFaultException: status=Bad_OutOfMemory, message=Not enough memory to complete the operation.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.milo.opcua.stack.client.UaStackClient.lambda$deliverResponse$5(UaStackClient.java:337)
	at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$Task.run(ExecutionQueue.java:119)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.milo.opcua.stack.core.UaServiceFaultException: status=Bad_OutOfMemory, description=Not enough memory to complete the operation.
	... 5 common frames omitted
17:21:22.794 [milo-shared-thread-pool-0] WARN  o.e.m.opcua.sdk.client.AddressSpace - Failed to create Node from Reference to ExpandedNodeId{ns=2, id=XBD.GML.ZDW_2110CY, serverIndex=0}
java.util.concurrent.CompletionException: UaServiceFaultException: status=Bad_OutOfMemory, message=Not enough memory to complete the operation.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.milo.opcua.stack.client.UaStackClient.lambda$deliverResponse$5(UaStackClient.java:337)
	at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$InlineTask.run(ExecutionQueue.java:154)
	at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$Task.run(ExecutionQueue.java:136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.milo.opcua.stack.core.UaServiceFaultException: status=Bad_OutOfMemory, description=Not enough memory to complete the operation.
	... 6 common frames omitted
17:21:22.794 [milo-shared-thread-pool-0] WARN  o.e.m.opcua.sdk.client.AddressSpace - Failed to create Node from Reference to ExpandedNodeId{ns=2, id=XBD.GML.ZDW_2206CY, serverIndex=0}
java.util.concurrent.CompletionException: UaServiceFaultException: status=Bad_OutOfMemory, message=Not enough memory to complete the operation.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.milo.opcua.stack.client.UaStackClient.lambda$deliverResponse$5(UaStackClient.java:337)
	at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$Task.run(ExecutionQueue.java:119)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.milo.opcua.stack.core.UaServiceFaultException: status=Bad_OutOfMemory, description=Not enough memory to complete the operation.
	... 5 common frames omitted
`  private void browseNode(String indent, OpcUaClient client, NodeId browseRoot) {
    try {
      List<? extends UaNode> nodes = client.getAddressSpace().browseNodes(browseRoot);

      for (UaNode node : nodes) {
        logger.info("{} Node={}", indent, node.getBrowseName().getName());
        if (node instanceof FolderTypeNode && !node.getBrowseName().getName().startsWith("_"))
          // recursively browse to children
          browseNode(indent + "  ", client, node.getNodeId());
      }
    } catch (UaException e) {
      logger.error("Browsing nodeId={} failed: {}", browseRoot, e.getMessage(), e);
    }
  }
}
`

OPC UA Server : KEPServerEX 6

**Comment by kevinherron** [comment]
This StatusCode comes from the server. Not a problem with the client.
