### ISSUE TITLE
Exceptions being logged when connecting to Unified Automation server

### ISSUE THREAD

**Issue by point85** [eclipse/milo#149]
This is more of a question than an issue, but I don't see a place to post just a question.

I am testing against the Unified Automation's ANSI C demo server with Milo client version 0.1.5.  The Build Info is 
BuildInfo{ProductUri=urn:UnifiedAutomation:UaDemoServerAnsiC, ManufacturerName=Unified Automation GmbH, ProductName=ANSI C SDK UA Sample Server, SoftwareVersion=V1.7.0 / 24fdd05441b0535756060718f3ac652a3d63e12b, BuildNumber=354, BuildDate=DateTime{utcTime=131139301650000000, javaDate=Mon Jul 25 07:22:45 PDT 2016}}

During the connect call to get a channel, this exception is logged:

2017-11-07 09:12:03.343 DEBUG ClientChannelManager - getChannel() while Idle
java.lang.Exception
	at org.eclipse.milo.opcua.stack.client.ClientChannelManager.getChannel(ClientChannelManager.java:68)
	at org.eclipse.milo.opcua.stack.client.UaTcpStackClient.connect(UaTcpStackClient.java:124)
	at org.eclipse.milo.opcua.sdk.client.OpcUaClient.connect(OpcUaClient.java:211)
	
at this source line:
            if (state.compareAndSet(currentState, nextState)) {
                logger.debug("getChannel() while Idle", new Exception());
				
subsequently a second exception is logged:

2017-11-07 09:12:03.358 DEBUG ClientSessionManager - getSession() while Inactive
java.lang.Exception
	at org.eclipse.milo.opcua.sdk.client.ClientSessionManager.getSession(ClientSessionManager.java:148)
	at org.eclipse.milo.opcua.sdk.client.OpcUaClient.getSession(OpcUaClient.java:606)
	at org.eclipse.milo.opcua.sdk.client.OpcUaClient.lambda$connect$1(OpcUaClient.java:212)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.eclipse.milo.opcua.stack.client.UaTcpStackClient.lambda$connect$0(UaTcpStackClient.java:125)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:739)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-11-07 09:12:03.359 DEBUG ClientSessionManager - Sending CreateSessionRequest...

at this source line:

            if (state.compareAndSet(currentState, creatingState)) {
                logger.debug("getSession() while Inactive", new Exception());
				
These exceptions do not appear to affect functionality.  Should Milo write to the log without creating an Exception object?

**Comment by kevinherron** [comment]
It's only logged if you have your logging level set to DEBUG or higher. The empty Exception is intentional - the stack trace is useful when trying to troubleshoot and figure out where the call to getSession() came from.
