### ISSUE TITLE
question about Callmethed invoke

### ISSUE THREAD

**Issue by OrangeAlex** [eclipse/milo#258]
hi, kevinherron
   when i want to implement the OPC UA Client and use the Callmethod() to access the OPC UA Server, this is  a exception throwed as fellows:
java.util.concurrent.CompletionException: UaException: status=Bad_ArgumentsMissing, message=The client did not specify all of the input arguments for the method.
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)[:1.8.0_141]
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)[:1.8.0_141]
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)[:1.8.0_141]
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:953)[:1.8.0_141]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)[:1.8.0_141]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)[:1.8.0_141]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)[:1.8.0_141]
        at org.eclipse.milo.opcua.stack.client.UaTcpStackClient.lambda$receiveResponse$13(UaTcpStackClient.java:294)[141:com.huawei.m2m.cig.opcua:1.0.0]
        at org.eclipse.milo.opcua.stack.core.util.ExecutionQueue$PollAndExecute.run(ExecutionQueue.java:107)[141:com.huawei.m2m.cig.opcua:1.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_141]
the log show me  that the client did not specify all of the input argument ,
i have a OPC UA Server which created by a software "UaExpert",when i create a Sever , it will initialize a lot of Node , so  i want to access one of method in them, it named "Multiply",
![methodinfo](https://user-images.githubusercontent.com/15887057/38234580-df02aa3e-3750-11e8-8081-9e179ba40850.PNG)
![methodinfo2](https://user-images.githubusercontent.com/15887057/38234657-16699802-3751-11e8-8bd3-f490fdd98e65.PNG)
so  how to access this method via the Callmethod, my code as fellows :

public void run(OpcUaClient client, CompletableFuture<OpcUaClient> future) throws Exception{
        log.error("OPC UA Client Run Test here!");
        client.connect().get();
        //call method
        NodeId objectId = NodeId.parse("ns=0;i=85");
        NodeId methodId = NodeId.parse("ns=4;s=Demo.Method.Multiply");
        callmethod(client,objectId,methodId,"'InputArguments','OutputArguments'")
                .exceptionally(ex->{
                    log.error("error invoking method() Demo.Method.Multiply",ex);
                    return null;
                }).thenAccept(v -> log.error("method return {}",v));
        future.complete(client);
    }
in my view ,  when i initialize the method id is the Demo.Method.Multiply , is that true ?
By the way, when i use the function callmethod, it request four input arguments, i have a question that what is the forth argument mean? if i want to access the "Multiply"Method Node , what argument should i use ?
      i am looking forwarding your response
      thank you very much

**Comment by kevinherron** [comment]
Have you looked at the [method example](https://github.com/eclipse/milo/blob/master/milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/MethodExample.java) yet?
