### ISSUE TITLE
OPC UA Client state unknown

### ISSUE THREAD

**Issue by sensubha** [eclipse/milo#758]
When connect to OPC UA TIA server, OPC UA Client is running and exchanging data for 7-8 hours. After that getting error in client as "OPC UA Client state unknown" and tag reading is stopped. What would be the probable reason and how to resolve?

**Comment by kevinherron** [comment]
You’ll have to provide a lot more information, log messages, Wireshark captures, etc...

“OPC UA Client state unknown” is not even a message that originates front his library.

**Comment by sensubha** [comment]
2021-02-09 02:30:49.5388 DEBUG [OPC]: Object NodeId: ns=3;s="OPCMethodAdhData_IDB", Method NodeId: ns=3;s="OPCMethodAdhData_IDB".Method.
2021-02-09 02:30:49.5520 DEBUG [OPC]: Object NodeId: ns=3;s="OPCMethodAdhData_IDB", Method NodeId: ns=3;s="OPCMethodAdhData_IDB".Method. Successful
2021-02-09 02:30:49.5520 DEBUG [OPC] Monitored tag event received: 127
2021-02-09 02:30:49.5520 DEBUG [OPC]: Object NodeId: ns=3;s="OPCMethodAdhData_IDB", Method NodeId: ns=3;s="OPCMethodAdhData_IDB".Method.
2021-02-09 02:30:49.6293 ERROR BadInvalidState
Opc.Ua.ServiceResultException: BadInvalidState
   at Opc.Ua.Client.Session.Call(NodeId objectId, NodeId methodId, Object[] args)
   at CUS.L1A.Handlers.OPCHandler.OPCHandler.CallAdhMethod(String methodIdString, String objectIdString) in D:\ProcessExpert\Standard\Src\CUS.Handlers\CUS.L1A.Handlers\OPCHandler\OPCHandler.cs:line 589
   at CUS.L1A.Managers.L1SignalManager.CallAdhMethod() in D:\ProcessExpert\Standard\Src\CUS.Managers\CUS.L1A.Managers\L1SignalManager.cs:line 720
2021-02-09 02:30:49.6762 DEBUG [OPC]: Object NodeId: ns=3;s="OPCMethodAdhData_IDB", Method NodeId: ns=3;s="OPCMethodAdhData_IDB".Method. Successful
2021-02-09 02:30:49.6762 DEBUG [OPC] Monitored tag event received: 130
2021-02-09 02:30:49.6762 DEBUG [OPC]: Object NodeId: ns=3;s="OPCMethodAdhData_IDB", Method NodeId: ns=3;s="OPCMethodAdhData_IDB".Method.
2021-02-09 02:30:49.6918 ERROR [OPC] Error during calling ADH method

**Comment by sensubha** [comment]
When restart the program, it again start tag reading and opc method calling.

**Comment by kevinherron** [comment]
These log messages are not from this library. I think you may be in the wrong place. Looks like .NET code.

**Comment by sensubha** [comment]
I am getting the error when I tried to connect S7 1500 PLC opc server from C# client which is developed using OPC UA Client

**Comment by kevinherron** [comment]
This is a Java library.
