### ISSUE TITLE
NullPointerException in SessionManager

### ISSUE THREAD

**Issue by ergouser** [eclipse/milo#82]
We have logs that report this exception for a while, but then seem to work correctly.  I may be able to run the OPC UA client that generated this if the cause is not obvious.

Uncaught Throwable executing ServiceRequestHandler: org.eclipse.milo.opcua.stack.core.application.UaStackServer$$Lambda$39/7373020@19f53f1 
java.lang.NullPointerException
	at org.eclipse.milo.opcua.sdk.server.SessionManager.validatePolicyId(SessionManager.java:511)
	at org.eclipse.milo.opcua.sdk.server.SessionManager.validateIdentityToken(SessionManager.java:490)
	at org.eclipse.milo.opcua.sdk.server.SessionManager.onActivateSession(SessionManager.java:452)
	at org.eclipse.milo.opcua.stack.server.tcp.UaTcpStackServer.receiveRequest(UaTcpStackServer.java:241)
	at org.eclipse.milo.opcua.stack.server.handlers.UaTcpServerSymmetricHandler.lambda$null$3(UaTcpServerSymmetricHandler.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by kevinherron** [comment]
The policyId coming from the client must be null. Should be easy to fix in the server, I'll fix it today.
