### ISSUE TITLE
Facing exception while performing browse operation

### ISSUE THREAD

**Issue by bibhudatta-sahu** [eclipse/milo#968]
Hello Everyone,

        When we starts browse operation, it continues without error for few minutes after that we are facing below exception.
 
[2022-04-19 13:02:15,189] – [milo-netty-event-loop-0] – [ERROR] – o.e.m.o.s.c.t.u.UascClientMessageHandler           : [remote=EmPilot1APM/10.8.4.59:56000] Exception caught: Connection reset by peer

java.io.IOException: Connection reset by peer

        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)

        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)

        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)

        at sun.nio.ch.IOUtil.read(IOUtil.java:192)

        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)

        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)

        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)

        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)

        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)

        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)

        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)

        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)

        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)

        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)

        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

        at java.lang.Thread.run(Thread.java:748)

[2022-04-19 13:02:15,198] – [milo-shared-thread-pool-61] – [WARN] – o.e.milo.opcua.sdk.client.SessionFsm               : [5] Keep Alive failureCount=2 exceeds failuresAllowed=1

[2022-04-19 13:02:16,213] – [epmtuscpltadintv2.azure-devices.net-d963bb0b-d685-4785-8b3e-df3487172799-36503549-Cxncdf6e2f2-45d8-45ee-9c3f-46b68d175e1e-azure-iot-sdk-IotHubReceiveTask] – [ERROR] –               : Browsing nodeId=NodeId{ns=4, id=qihg:kjhhumidity.cntdeadband} failed: UaException: status=Bad_ConnectionRejected, message=io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: Machine1/12.9.5.60:23000

java.util.concurrent.ExecutionException: UaException: status=Bad_ConnectionRejected, message=io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: Machine1/12.9.5.60:23000

 Can anyone please provide any reason why this is happening and how to handle this exception.
 
 Thanks,
 Bibhudatta

**Comment by kevinherron** [comment]
I think you might be overwhelming the server you are connected to with your (recursive?) browse.

>[ERROR] – o.e.m.o.s.c.t.u.UascClientMessageHandler : [remote=EmPilot1APM/10.8.4.59:56000] Exception caught: Connection reset by peer

The server closed the connection.

>[WARN] – o.e.milo.opcua.sdk.client.SessionFsm : [5] Keep Alive failureCount=2 exceeds failuresAllowed=1

The server isn't responding to the "keep alive" reads targeting the server State. Possibly because it's overwhelmed?

>[ERROR] – : Browsing nodeId=NodeId{ns=4, id=qihg:kjhhumidity.cntdeadband} failed: UaException: status=Bad_ConnectionRejected, message=io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: Machine1/12.9.5.60:23000
java.util.concurrent.ExecutionException: UaException: status=Bad_ConnectionRejected, message=io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: Machine1/12.9.5.60:23000

Looks like at this point the client is reconnecting and getting a connection refused error. Maybe the server is offline now? Not sure.
